#-----------------------------------------
# Program information
#-----------------------------------------

# The program is not relocable (due to data) and should be loaded at
# address PROGRAM_ADDR in the target system
SRC= mpf1-helpus.asm
PROGRAM_ADDR= 0x1800


# Compile the loader to be loaded dynamically in the RAM.
# We request the generation of an Hex file that contains
# the actual target addresses
#BURN_ROM= 1


#-----------------------------------------
# Utility makefile with compilation rules
#-----------------------------------------
include ../../utils/utils.make
